// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomNumberService.RandomNumberDatabase;

namespace RandomNumberConsole.Migrations
{
    [DbContext(typeof(RandomNumberDbContext))]
    partial class RandomNumberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("RandomNumberService.RandomNumberDatabase.RandomNumber", b =>
                {
                    b.Property<int>("RandomNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ServiceCallRetryRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("RandomNumberId")
                        .HasName("PrimaryKey_RandomNumberId");

                    b.ToTable("RandomNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
